# Generated by Django 5.0.2 on 2024-04-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourismModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('BlogContent', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('Zip', models.IntegerField()),
                ('Image', models.ImageField(upload_to='Images/')),
            ],
        ),
    ]
