# Generated by Django 5.0.2 on 2024-04-20 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OdishaTourismApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismmodel',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
