# Generated by Django 5.0.2 on 2024-05-04 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OdishaTourismApp', '0003_culturemodel_delete_tourismmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=25)),
                ('FoodlDetails', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='Images/')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
