# Generated by Django 5.0.2 on 2024-05-05 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OdishaTourismApp', '0004_foodmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolkDanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FolkDanceName', models.CharField(max_length=25)),
                ('FolkDanceDetails', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='Images/')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
