# Generated by Django 5.0.2 on 2024-05-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OdishaTourismApp', '0005_folkdancemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folkdancemodel',
            old_name='City',
            new_name='District',
        ),
    ]
